# Generated by Django 5.1.6 on 2025-03-05 22:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInDes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadmap',
            name='geom',
        ),
        migrations.AddField(
            model_name='uploadmap',
            name='dbf_file',
            field=models.FileField(blank=True, default='maps/default.dbf', help_text='Upload .dbf file', null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='uploadmap',
            name='shp_file',
            field=models.FileField(blank=True, default='maps/default.dbf', help_text='Upload .shp file', null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='uploadmap',
            name='shx_file',
            field=models.FileField(blank=True, default='maps/default.dbf', help_text='Upload .shx file', null=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='uploadmap',
            name='name',
            field=models.CharField(help_text='Name of the map', max_length=255, unique=True),
        ),
    ]
